"""anomaly canonical artifact columns

Revision ID: 47c84e7640e2
Revises: b7c4e661ad2f
Create Date: 2026-07-03 16:04:51.043142
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "47c84e7640e2"
down_revision = "b7c4e661ad2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Anomalies are derived data (regenerated by every detection run), so the
    # table is cleared rather than backfilling the new NOT NULL columns.
    op.execute("delete from anomalies")
    op.add_column(
        "anomalies", sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.add_column(
        "anomalies", sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.add_column("anomalies", sa.Column("recommended_action", sa.Text(), nullable=False))
    op.create_index("ix_anomalies_day_issue", "anomalies", ["day", "issue"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_anomalies_day_issue", table_name="anomalies")
    op.drop_column("anomalies", "recommended_action")
    op.drop_column("anomalies", "metrics")
    op.drop_column("anomalies", "signals")
    # ### end Alembic commands ###
