"""conversation issues and issue catalog

Revision ID: 645598213ba7
Revises: 8480de9da49b
Create Date: 2026-07-03 14:47:40.589776
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "645598213ba7"
down_revision = "8480de9da49b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_catalog",
        sa.Column("canonical_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("first_seen_day", sa.Integer(), nullable=False),
        sa.Column("example_count", sa.Integer(), nullable=False),
        sa.Column(
            "representative_examples", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("canonical_name"),
    )
    op.create_table(
        "conversation_issues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(), nullable=False),
        sa.Column("customer_description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("customer_impact", sa.String(), nullable=False),
        sa.Column("product", sa.String(), nullable=False),
        sa.Column("symptoms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("catalog_matched", sa.Boolean(), nullable=False),
        sa.Column("catalog_confidence", sa.Float(), nullable=False),
        sa.Column("resolution_status", sa.String(), nullable=False),
        sa.Column("resolution_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_issues_canonical_name"),
        "conversation_issues",
        ["canonical_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_issues_catalog_matched"),
        "conversation_issues",
        ["catalog_matched"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_issues_conversation_id"),
        "conversation_issues",
        ["conversation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversation_issues_conversation_id"), table_name="conversation_issues")
    op.drop_index(op.f("ix_conversation_issues_catalog_matched"), table_name="conversation_issues")
    op.drop_index(op.f("ix_conversation_issues_canonical_name"), table_name="conversation_issues")
    op.drop_table("conversation_issues")
    op.drop_table("issue_catalog")
    # ### end Alembic commands ###
