"""pipeline runs audit trail

Revision ID: 8480de9da49b
Revises: 02716f579f66
Create Date: 2026-07-03 10:34:05.017909
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "8480de9da49b"
down_revision = "02716f579f66"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stage_key", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pipeline_runs_stage_key_started_at",
        "pipeline_runs",
        ["stage_key", "started_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pipeline_runs_stage_key_started_at", table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    # ### end Alembic commands ###
